import "./globals.css";
import { MonaSansWide } from "./fontLoader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={MonaSansWide.className}>
        {children}
      </body>
    </html>
  );
}
